---
- name: Install nginx and modules
  apt:
    name:
    - nginx
    - libnginx-mod-http-fancyindex
    state: present
    update_cache: yes
- name: Create nginx default snippet directory
  file:
    path: "/etc/nginx/site-default.d"
    state: directory

- name: Create nginx default config
  template:
    src: "default.j2"
    dest: "/etc/nginx/sites-available/default"
  notify:
    - Reload nginx

- meta: flush_handlers

- name: Create nginx default config
  template:
    src: "default.j2"
    dest: "/etc/nginx/sites-available/default"
  notify:
    - Reload nginx
