- name: Install etcd client package
  apt: name=etcd-client state=present
- name: Copy the etcd CA
  copy:
    src: "etcd-ca.pem"
    dest: "/etc/ssl/etcd/"
- name: Copy the etcd client key
  copy:
    src: "{{ inventory_hostname}}/etcd-client.key.pem"
    dest: "/etc/ssl/etcd/"
- name: Copy the etcd client cert
  copy:
    src: "{{ inventory_hostname}}/etcd-client.cert.pem"
    dest: "/etc/ssl/etcd/"
- name: Make etcd v3 API the default
  copy:
    dest: "/etc/profile.d/etcd.sh"
    content: |
      export ETCDCTL_API=3
      export ETCDCTL_CACERT=/etc/ssl/etcd/etcd-ca.pem
      export ETCDCTL_CERT=/etc/ssl/etcd/etcd-client.cert.pem
      export ETCDCTL_KEY=/etc/ssl/etcd/etcd-client.key.pem
      export ETCDCTL_ENDPOINTS={{etcd_endpoints}}
- name: Create etcd client configuration settings
  copy:
    dest: "/etc/etcd-client.json"
    content: |
      {
        "CACERT": "/etc/ssl/etcd/etcd-ca.pem",
        "CERT": "/etc/ssl/etcd/etcd-client.cert.pem",
        "KEY": "/etc/ssl/etcd/etcd-client.key.pem",
        "ENDPOINT": "{{etcd_endpoint}}",
        "ENDPOINTS": "{{etcd_endpoints}}"
      }
