---
- hosts: all:!UCI-Nodes
  become: true
  roles:
    # - users
    - common-ffmuc
    - wireguard

- hosts: Backbone
  strategy: free
  become: true
  roles:
    - no-vrf
    - lab-net
    # - wireguard-backbone

- hosts: etcd_cluster
  become: true
  roles:
    - etcd

- hosts: etcd_clients
  become: true
  roles:
    - etcd-client

- hosts: Concentrators
  become: true
  roles:
    - nginx
    - wireguard-concentrator
    # - bind
    # - bind-reverse
    # - chrony
