- name: install emqttd 
  apt:
    deb: http://emqtt.io/downloads/latest/debian9-deb
- name: install python3-etcd 
  apt:
    name: python3-etcd
    state: present
- name: copy emqttd cluster manager
  copy:
    src: emqtt_cluster_manager.py 
    dest: /usr/bin/emqtt_cluster_manager
    mode: 0777
  notify:
    - Restart emqttd_cluster_manager
- name: configure emqttd
  template:
    src: emq.j2
    dest: /etc/emqttd/emq.conf
    owner: emqtt
    group: emqtt
    mode: 0644
- name: stop emqtt service 
  service:
    name: emqttd 
    state: stopped 
- name: disable emqtt service 
  service:
    name: emqttd 
    enabled: no 
#- name: remove emqttd from init
#  file:
#    path: /etc/init.d/emqttd
#    state: absent
- name: copy emqtt service file
  copy:
    src: emqttd.service
    dest: /etc/systemd/system/emqttd.service
- name: copy emqttd cluster manager service file
  copy:
    src: emqttd_cluster_manager.service
    dest: /etc/systemd/system/emqttd_cluster_manager.service
  notify:
    - Restart emqttd_cluster_manager
- name: reload systemd service files 
  systemd:
    name: emqttd 
    daemon_reload: yes
- name: reload systemd service files 
  systemd:
    name: emqttd_cluster_manager 
    daemon_reload: yes
- name: configure emqttd cluster manager service (systemd) 
  systemd:
    name: emqttd_cluster_manager
    enabled: yes
  notify:
    - Restart emqttd
- name: configure emqtt service (systemd) 
  systemd:
    name: emqttd 
    enabled: yes
  notify:
    - Restart emqttd
