- name: Configure routing protocol name
  lineinfile:
    dest: "/etc/iproute2/rt_protos"
    line: "23\tfreifunk"
    state: absent
- name: Configure routing table name
  lineinfile:
    dest: "/etc/iproute2/rt_tables"
    line: "10\tfreifunk"
    state: absent
- name: Configure sysctl for vrf
  ansible.builtin.file:
    state: absent
    path: "/etc/sysctl.d/20-vrf.conf"
# Replaced by networkd
- name: Add networkd vrf network
  ansible.builtin.file:
    state: absent
    path: "/etc/systemd/network/10-vrf-freifunk.network"
  notify:
    - Restart systemd-networkd
- name: Add networkd vrf netdev
  ansible.builtin.file:
    state: absent
    path: "/etc/systemd/network/10-vrf-freifunk.netdev"
  notify:
    - Restart systemd-networkd
- name: Add VRF-specific resolv.conf
  ansible.builtin.file:
    state: absent
    path: '/etc/resolv.conf.freifunk'
- name: Add enter-freifunk helper script
  ansible.builtin.file:
    state: absent
    path: '/root/enter-freifunk'
