- name: Configurate etcd service with a longer startup timeout and automatic restart
  copy:
    src:  'startup.conf'
    dest: '/etc/systemd/system/etcd.service.d/'
    mode: 0644
- name: Install etcd packages
  apt:
    state: present
    name:
      - etcd-client
      - etcd-server
  register:
    etcd_install
- name: Copy the etcd CA
  copy:
    src: "etcd-ca.pem"
    dest: "/etc/ssl/etcd/"
- name: Copy the etcd server key
  copy:
    src: "{{ inventory_hostname}}/etcd-server.key.pem"
    dest: "/etc/ssl/etcd/"
    mode: 0640
    group: "etcd"
- name: Copy the etcd server cert
  copy:
    src: "{{ inventory_hostname}}/etcd-server.cert.pem"
    dest: "/etc/ssl/etcd/"
    mode: 0640
    group: "etcd"
- name: Copy the etcd client key
  copy:
    src: "{{ inventory_hostname}}/etcd-client.key.pem"
    dest: "/etc/ssl/etcd/"
- name: Copy the etcd client cert
  copy:
    src: "{{ inventory_hostname}}/etcd-client.cert.pem"
    dest: "/etc/ssl/etcd/"
- name: Enable etcd service
  command: "systemctl enable etcd"
  when: etcd_install.changed
- name: Configure etcd
  template:
    src: "etcd.j2"
    dest: "/etc/default/etcd"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - Restart etcd
- name: Make etcd v3 API the default
  copy:
    dest: "/etc/profile.d/etcd.sh"
    content: |
      export ETCDCTL_API=3
      export ETCDCTL_CACERT=/etc/ssl/etcd/etcd-ca.pem
      export ETCDCTL_CERT=/etc/ssl/etcd/etcd-client.cert.pem
      export ETCDCTL_KEY=/etc/ssl/etcd/etcd-client.key.pem
      export ETCDCTL_ENDPOINTS={{etcd_endpoints}}
- name: Create etcd client configuration settings
  copy:
    dest: "/etc/etcd-client.json"
    content: |
      {
        "CACERT": "/etc/ssl/etcd/etcd-ca.pem",
        "CERT": "/etc/ssl/etcd/etcd-client.cert.pem",
        "KEY": "/etc/ssl/etcd/etcd-client.key.pem",
        "ENDPOINT": "{{etcd_endpoint}}",
        "ENDPOINTS": "{{etcd_endpoints}}"
      }
- name: Create etcd cluster data init script
  template:
    src: "etcd-init.sh"
    dest: "/root/etcd-init.sh"
    mode: "0700"
- name: Initialize etcd cluster data
  command: "/root/etcd-init.sh"
- name: Create etcd snapshot service
  template:
    src: "etcd-snapshot.service.j2"
    dest: "/etc/systemd/system/etcd-snapshot.service"
    owner: "root"
    group: "root"
    mode: "0644"
- name: Create etcd snapshot timer
  template:
    src: "etcd-snapshot.timer.j2"
    dest: "/etc/systemd/system/etcd-snapshot.timer"
    owner: "root"
    group: "root"
    mode: "0644"
- name: Enable and start snapshot timer
  systemd:
    daemon_reload: yes
    name: etcd-snapshot.timer
    state: started
    enabled: yes
