---
- name: Update apt
  apt:
    update_cache: true
- name: Install standard packages
  become: true
  apt:
    state: present
    name:
      - linux-image-generic
      - rsync
      - htop
      - curl
      - tcpdump
      - mtr
      - strace
      - signify-openbsd
