---
- name: Install Golang compiler
  ansible.builtin.apt:
    state: present
    name:
      - golang

- name: Install etcd-tools
  ansible.builtin.shell:
    cmd: |
      GOBIN=/usr/local/bin go install "github.com/freifunkMUC/etcd-tools/...@17368fceef99947ea3a97f4d2c9284f9e061413e"
  args:
    creates: "/usr/local/bin/etcdconfigweb"
