---
- name: Install Golang compiler
  ansible.builtin.apt:
    state: present
    name:
      - golang

- name: Get old etcdconfigweb checksum
  ansible.builtin.stat:
    path: /usr/local/bin/etcdconfigweb
    get_checksum: true
    follow: true
    get_attributes: false
    get_mime: false
  register: old_checksum

- name: Install etcd-tools
  ansible.builtin.shell:
    cmd: |
      GOBIN=/usr/local/bin go install "github.com/freifunkMUC/etcd-tools/...@a2cfc9b71a63780142402996a1d8e7c3d101ce63"
  changed_when: false

- name: Get new etcdconfigweb checksum
  ansible.builtin.stat:
    path: /usr/local/bin/etcdconfigweb
    get_checksum: true
    follow: true
    get_attributes: false
    get_mime: false
  register: new_checksum

- name: Check if etcd-tools have changed
  ansible.builtin.assert:
    that: true
    quiet: true
  changed_when: true
  when:
    - not old_checksum.stat.exists or
      old_checksum.stat.checksum != new_checksum.stat.checksum
  notify:
    - Restart etcd-config-web
