---
- name: Create wireguard configuration
  template:
    src: 'wireguard.j2'
    dest: '/etc/systemd/network/20-wg-nodes.netdev'
    group: "systemd-network"
    mode: 0640  # permission required systemd-networkd
  notify:
    - Restart systemd-networkd

- name: Create wireguard interfaces
  template:
    src: 'interface.j2'
    dest: '/etc/systemd/network/20-wg-nodes.network'
    group: "systemd-network"
    mode: 0644
  notify:
    - Restart systemd-networkd
